version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5001:5000"
    environment:
      - MLFLOW_HOST=0.0.0.0
      - MLFLOW_PORT=5000
      - MLFLOW_BACKEND_STORE_URI=sqlite:////mlflow/mlflow.db
    volumes:
      - mlflow-data:/mlflow
    user: root 
    command: >
      mlflow server 
      --backend-store-uri sqlite:////mlflow/mlflow.db 
      --default-artifact-root /mlflow/artifacts
    restart: unless-stopped
    networks:
      - app-network

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - mlflow-data:/mlflow
    ports:
      - "8000:8000"
      - "8001:8001"
    restart: unless-stopped
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8502:8501"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mlflow-data: