{
 "title": "MLops",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Memory Utilisation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_network_bytes_sent[1m])/60",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(system_network_bytes_recv[1m])/60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(model_init_requests_total[1m])) by (method)*60",
     "legendFormat": "model_init"
    },
    {
     "expr": "sum(rate(last_trained_date_requests_total[1m])) by (method)*60",
     "legendFormat": "get_last_trained_date"
    },
    {
     "expr": "sum(rate(predict_for_date_requests_total[1m])) by (method)*60",
     "legendFormat": "predict_for_next_day"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "latency per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(model_init_request_latency_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "model_init"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(last_trained_date_request_latency_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "get_last_trained_date"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(predict_for_date_request_latency_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum by (client_ip) (api_requests_per_ip_total)",
     "legendFormat": "{{client_ip}}"
    }
   ]
  },
  {
   "title": "System File Handles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_file_handles", "legendFormat": "__auto" }
   ]
  }
 ]
}