global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'python-app'
    static_configs:
      - targets: ['localhost:8001']
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'system_metrics'
    static_configs:
      - targets: ['localhost:9100']